#!/bin/bash

if command -v podman &> /dev/null; then
  echo podman
elif  command -v docker &> /dev/null; then
  echo docker
else
  echo "No supported container engine detected. Please install Podman or Docker."
  exit 1
fi
