#!/bin/bash

echo "Enabling and starting systemd service..."
sudo cp setup/mcullenm-dev-2.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable mcullenm-dev-2
sudo systemctl start mcullenm-dev-2
